### ISSUE TITLE
Breaks on my Browser

### ISSUE THREAD

**Issue by AnthoniG** [rmariuzzo/react-new-window#1]
Love this, as I read the main article. Could not find a way to comment though, but that's beside the by.

I use Palemoon for my browser (as do most of my colleagues). It is a fork of the Firefox browser but with less crashing.

Anyway, sad to say it does not work on this browser. Tried it in Chrome and it worked perfectly.

When I get time, I will take a look at what is going on and see if I can fix it. However I write solely in Typescript, so I might need to convert the component. If I do, I will send you a copy of it :)

Regards
Anthoni

**Comment by raptox** [comment]
seems to work on my Firefox
