### ISSUE TITLE
cannot add eventlisteners to the popup window

### ISSUE THREAD

**Issue by ZakiMohammad** [rmariuzzo/react-new-window#105]
when i try to add event listener to popup its getting applied on parent window how do i add blur event on popup window

**Comment by ThibautMarechal** [comment]
Hi @ZakiMohammad I managed to do that inside the onOpen callBack props
`<NewWindow onOpen={(newWindow) => newWindow.addEventListener('blur', console.log)}>{children}</NewWindow>`
