### ISSUE TITLE
Close new window on parent tab close.

### ISSUE THREAD

**Issue by rodrigo-sosa-wizeline** [rmariuzzo/react-new-window#114]
Is there a way to implement this behavior? currently the only way to close the window is by closing the browser completely.

**Comment by rmariuzzo** [comment]
Hey there! I apologize for the very long reply. Currently, you can handle using the `onOpen` callback to capture the window instance.

Here's a simplified example:
```tsx
const [popup, setPopup] = useState()

useEffect(() => {
  window.addEventListener('unload', () => {
    if (popup) popup.close()
  })
}, [])

return <NewWindow onOpen={e => setPopup(e)} />
```
