### ISSUE TITLE
Type definition bug: React 18 requires `children` be defined.

### ISSUE THREAD

**Issue by disambiguator** [rmariuzzo/react-new-window#118]
The package currently causes type errors on React 18 because it does not explicitly define children as a prop.

**Comment by RobRendell** [comment]
In the meantime, you can create a `react-new-window.d.ts` definition file for react-new-window in your own @types folder which updates the prop definition:
```
import React, {PropsWithChildren} from 'react';

declare module 'react-new-window' {
    import {INewWindowProps} from 'react-new-window';

    export default class NewWindow extends React.PureComponent<PropsWithChildren<INewWindowProps>> {};
}
```
