### ISSUE TITLE
Passing menubar=true or menubar=1 or menubar=yes doesn't work

### ISSUE THREAD

**Issue by danielohirsch** [rmariuzzo/react-new-window#123]
Menubar doesn't show up... Need it for the print menu feature of the opened window.

**Comment by rmariuzzo** [comment]
As per [the docs for window features](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) `menubar` is not a valid feature. Also the docs adds:
> Popups don't have a menu toolbar, whereas new tabs use the user interface of the browser window; therefore, many users prefer tab-browsing because the interface remains stable.
