### ISSUE TITLE
maintenance of library

### ISSUE THREAD

**Issue by AdityaKirad** [rmariuzzo/react-new-window#127]
I don't know why the maintenance of this awesome library is stopped currently the version of react is 18 and this library only supports react version up to 16 I have many issues while using this library with my Next.js projects which are using react 18 as dependencies on of the issues I'm still facing when I use this library to open sign-in page from `next-auth` library I have to do more then one clicks so that new window opens up

**Comment by rmariuzzo** [comment]
I'm aiming on focusing more time on this library this week and next week.

**Comment by AdityaKirad** [comment]
> I'm aiming on focusing more time on this library this week and next week.

It will be better if you if you convert the NewWindow class component to function component as they give more readability to code, hooks are now being more used and they only work with function component etc

**Comment by nmathew98** [comment]
@rmariuzzo can I be assigned to this?

**Comment by rmariuzzo** [comment]
Yes @nmathew98 we can work together on this.

@AdityaKirad I apologize to you and the community for long replies. The main reason, I was away is because of my health. However, now I want to create a small habit to not only address issues but also to add maintainer to some of my libraries.

**Comment by rmariuzzo** [comment]
That said, I'm checking on the React 18 support.

**Comment by rmariuzzo** [comment]
[Released a first version](https://github.com/rmariuzzo/react-new-window/releases/tag/v1.0.0) with basic React 18 support. Will continue to triage other issues.
