### ISSUE TITLE
How can i get the URL & queries of new opened window?

### ISSUE THREAD

**Issue by ilhamgum** [rmariuzzo/react-new-window#138]
Is there anything returned from onUnload, im trying to log but only get null

```
<NewWindow
      name="Payment"
      url={url}
      onUnload={(e) => console.log(e)} // only return null
></NewWindow>
```

or is it any way i can accessing the URL & Queries of new opened window? im using NextJS.

**Comment by rmariuzzo** [comment]
Unfortunately, we are only passing `null` to the `unload` function.
https://github.com/rmariuzzo/react-new-window/blob/06533bee6e774fac538db769a932cd69c97eab8f/src/NewWindow.js#L186-L188

I think you already have access to the scoped variables `url`. Maybe you could write it as:
```tsx
<NewWindow
      name="Payment"
      url={url}
      onUnload={() => console.log(url)}
></NewWindow>
```

Let me know if that works for you.

**Comment by rmariuzzo** [comment]
If you think otherwise, I'm happy to reopen this or another ticket with the specifics.
