### ISSUE TITLE
center prop doesn't work, window always located in top left of screen

### ISSUE THREAD

**Issue by austintackaberry** [rmariuzzo/react-new-window#141]
Regardless of whether I set it to parent or screen, it is always in the top left of my screen.

Ubuntu 22.04
Chrome Version 108.0.5359.71 (Official Build) (64-bit)
React 18.2
react-new-window 1.0.1

**Comment by austintackaberry** [comment]
Checked the code, realized I needed to add features prop with width and height fields and it worked!

**Comment by eriknyk** [comment]
I think that it's still an issue, since without specifying default width & height it uses defaults and the window should be centered according the center prop. It's hard to figure out that it's not centered bacause you didn't specify features prop.
@austintackaberry consider re-open it please.
