### ISSUE TITLE
How do you get the "document" of the new window ?

### ISSUE THREAD

**Issue by axelmy318** [rmariuzzo/react-new-window#150]
Hello,
I've been trying to put a listener on the window size but it always get the main window.
Does anyone knows how to access the "document" or "window" variable of the new window ?
Even document.getElementById() doesn't work in a useLayoutEffect when trying to get a DOM element in that new page.
Thanks :)

New window : 
![image](https://user-images.githubusercontent.com/82584433/212937122-38bf98ca-62e0-427b-8eb9-3ab555f89849.png)

NewWindowContent
![image](https://user-images.githubusercontent.com/82584433/212937246-47d4e981-f99f-445b-baba-7dd04293575e.png)

**Comment by gnekoz** [comment]
Hi, you should get the new window object as parameter in the onOpen callback

**Comment by axelmy318** [comment]
Thanks. I ended up making my own package but I hope your answer can be useful to someone else
