### ISSUE TITLE
package.json main points to non-existing file

### ISSUE THREAD

**Issue by pocesar** [rmariuzzo/react-new-window#16]
package.json main field currently points to "src/react-new-window.js" but the file doesn't exist, doesn't work with Typescript + Parcel at the moment without changing configs. the file is `src/NewWindow.js`

**Comment by rmariuzzo** [comment]
Can you create a PR for that?

**Comment by pocesar** [comment]
there are two PR's that fix both issues 👍

**Comment by rmariuzzo** [comment]
This was fixed.
