### ISSUE TITLE
Module not found: Can't resolve 'react-new-window' 

### ISSUE THREAD

**Issue by Louis-Chen** [rmariuzzo/react-new-window#17]
react version 16.2.0

had tried to delete package-lock.json && yarn.lock

**Comment by darrencrossley** [comment]
It seems the 0.0.8 version on NPM was pushed without umd or es build folders, can this be fixed?

**Comment by rmariuzzo** [comment]
@Louis-Chen / @darrencrossley  I apologize for the issues this raised. I just published v.0.0.9 with umd/es build folders. 🙇
