### ISSUE TITLE
copyStyles not working on Chrome 64+

### ISSUE THREAD

**Issue by rafaelkillua** [rmariuzzo/react-new-window#18]
I can't copy the styles from parent to children, Chrome gives me an error:

> DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

I did some searching and seems that Chrome 64+ have this issue...

> Chrome 64.0.3282.0 (released January 2018, [commit link](https://chromium.googlesource.com/chromium/src/+/a4ebe08c91e29140e700c7bae9b94f27a786d1ca)) includes a change to security rules for stylesheets.

And a possible fix:

[odoo@commit](https://github.com/odoo/odoo/commit/a6e66131ce5b676ccc888ec5b1011d0946dc3907)

**Comment by rafaelkillua** [comment]
I've done something wrong, now it is copying the styles, but still throwing the error...

**Comment by gianpaj** [comment]
I'm also getting this error though the styles seemed to be copying.

```
DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
```

Chrome v75
react-new-window v0.1.1

**Comment by brspurri** [comment]
Same. This issue should be reopened.
