### ISSUE TITLE
JEST Error! Can not find module 'react-new-window' .... 

### ISSUE THREAD

**Issue by j-rayhan** [rmariuzzo/react-new-window#20]
![test-error](https://user-images.githubusercontent.com/21338587/48347844-b24c3380-e6a9-11e8-9065-6929a11d2cc6.png)

**Comment by rafser01** [comment]
Pull #21 
Hope it will work.

**Comment by bypie5** [comment]
@rmariuzzo mentioned 0.0.9 would fix this issue, however, this issue does not disappear.

**Comment by rmariuzzo** [comment]
Sorry for long delay on this, will check later today.

**Comment by szwbuaa** [comment]
This issue still exists in 0.0.11.

**Comment by rmariuzzo** [comment]
This seems to be really fixed now. Also, [I'm adding tests to this library](https://github.com/rmariuzzo/react-new-window/tree/next).
