### ISSUE TITLE
Open window in print mode

### ISSUE THREAD

**Issue by rivkiroten** [rmariuzzo/react-new-window#25]
Hi,
I was wondering if it's possible to open a new window in print mode, with a print dialog box, using this library.
Thanks,

**Comment by Valerika** [comment]
not working for me @chrisjpatty

**Comment by kevinch** [comment]
@Valerika i used @chrisjpatty 's hints this way:
```
<NewWindow r={ref => (this.myReport = ref)}>
  <SomeComponent />
</NewWindow>
```
And within `<SomeComponent />`:
```
handlePrint = () => {
  this.props.r.window.print()
}

...

r: PropTypes.any,
```

**Comment by AidanNichol** [comment]
There is another way. ```<NewWindow/>``` has on undocumented property **onOpen** that is passed a handle to the window.
The following worked for me
```
<NewWindow onOpen={win=>win.print()} >
<SomeComponent />
</NewWindow>
```

**Comment by rmariuzzo** [comment]
The `onOpen` prop was added to the docs.
