### ISSUE TITLE
Issue with next and hot-dev-client

### ISSUE THREAD

**Issue by a-robin** [rmariuzzo/react-new-window#29]
Hi guys, I aam just starting to use this package that I find amazing.

Only problem is that I can't use it once my full project is being recompiled by the hot-dev-client from nextjs and pops this error:

![image](https://user-images.githubusercontent.com/20032603/53941907-4d31a900-40b1-11e9-9af0-6119089b66ae.png)

I am not sure how to deal with that yet, any idea ?

Thanks

**Comment by rmariuzzo** [comment]
I believe this was fixed in: https://github.com/rmariuzzo/react-new-window/commit/0f94ad55105c4b7c3d6203ec9a1c54b3af36f488
