### ISSUE TITLE
Installation and use of package causes Jest error 

### ISSUE THREAD

**Issue by sshadmand** [rmariuzzo/react-new-window#32]
Works fine in app, but fails test due to some known reason in NewWindow.js from importing React.
> "react-new-window": "^0.0.12"
> "jest": "20.0.4"
```
 ● Test suite failed to run

    /Users/seanshadmand/repos/konch/konch-www/node_modules/react-new-window/src/NewWindow.js:6
    import React from 'react'
    ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/Script
```

**Comment by rmariuzzo** [comment]
This was probably fixed with: https://github.com/rmariuzzo/react-new-window/commit/0f94ad55105c4b7c3d6203ec9a1c54b3af36f488
