### ISSUE TITLE
Open multiple tabs in the same external window

### ISSUE THREAD

**Issue by informvisu** [rmariuzzo/react-new-window#43]
Hi @rmariuzzo,
My usecase is to open a new tab on the same external window on each form submit.
The form on the parent contains IP Address, username and password. No need to maintain state beyond the form submit.
The tabs to mimic Multi-Tabbed Putty (using xterm and socket.io in MERN) and user closes them once done.
Is there a way to do this?
Much appreciated your hep.

**Comment by rmariuzzo** [comment]
Hi! Did some research, doesn't seem to be possible in current web browser.

Note: I apologize for the long reply. Also, will close this issue. However, I'm more than willing to address that if that's possible. I don't remember to have seen tabs opening in a popup.
