### ISSUE TITLE
requestAnimationFrame not called in NewWindow

### ISSUE THREAD

**Issue by arranlomas** [rmariuzzo/react-new-window#51]
using `requestAnimationFrame` doesn't work when used inside `NewWindow` if the window is fullscreen on a new desktop on MacOS 10.14.4.

This isn't specific to this library but I couldn't see much else online discussing this and wonder if this library can address this issue.

Here is an example snippet:

```tsx
function windowTest() {
    const features = { width: '600px', height: '640px' };
    const windowFeatures = toWindowFeatures(features);
    const outputWindow = window.open('', 'output', windowFeatures);
    if(!outputWindow){
        console.log('Could not create new window');
        return;
    }
    const outputContainer = outputWindow.document.createElement('div');
    outputWindow.document.body.appendChild(outputContainer);
    const animateTest = () => {
        console.log('animate test');
        outputWindow.requestAnimationFrame(() => animateTest())
    };
    animateTest()
}
```

`animateTest` is only called while the parent window that called `windowTest` is visible.

**Comment by rmariuzzo** [comment]
Hey there! I'm sorry for the very long reply. I tried the following code and I didn't see any issue on Mac 11.7.1:

```tsx
  <NewWindow
    onOpen={(popup) => popup.requestAnimationFrame(() => console.log("test"))}
  >
```
