### ISSUE TITLE
NewWindow does not repeat open after close

### ISSUE THREAD

**Issue by wsgrant** [rmariuzzo/react-new-window#53]
I am using the NewWindow in the following manner...

![image](https://user-images.githubusercontent.com/50171437/64725527-610ffa80-d49a-11e9-877b-121e828c8a65.png)

...calling NewWindow if a variable is set to true in state.  otherwise null.

However, if the window is closed, when I attempt to reopen, it does not do so; only after forcing page refresh.

**Comment by wsgrant** [comment]
disregard.  found issue with my own code.

**Comment by Crystal-Moon** [comment]
hello, how did you solve it? I have the same problem 😞

**Comment by utkarsh447** [comment]
Hi, I am stuck on the same issue, I am unable to reopen the window after closing it. Can you please share a minimal logic to solve this issue? I will greatly appreciate that.
