### ISSUE TITLE
Get current window url

### ISSUE THREAD

**Issue by namhnz** [rmariuzzo/react-new-window#54]
The "url" prop is the initial URL which the new window used, and it doesn't change after that. But sometimes I need to get the current URL of the window. So please add the ability to get it, or have onUrlChange event to detect when it changed.

**Comment by raymondshiner** [comment]
Any updates on this? This feature is like necessary for this window to be usable.

**Comment by OzdemirEmrah** [comment]
Hello, this is not possible according to the features provided by the window.open() method, and it should not be possible in terms of web security.

**Comment by rmariuzzo** [comment]
Although you can have access to the window instance via `onOpen`, there's a security concern specially when visiting another host. If you want to access the URL from within the same origin you can try with:

```tsx
<NewWindow
  onOpen={popup => console.log(popup.location.href)}
/>
```
