### ISSUE TITLE
import error in index.d.ts

### ISSUE THREAD

**Issue by AbhishekPratap05** [rmariuzzo/react-new-window#55]
Current import statements are throwing errors.

`import React from 'react'`
`import ReactDOM from 'react-dom'`

> /node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

> /node_modules/@types/react-dom/index"' has no default export.

If i change it to,
`import * as React from 'react'`
`import * as ReactDOM from 'react-dom'`
works fine, can you please look into it.

#### I am using React with TypeScript

**Comment by rmariuzzo** [comment]
I apologize for the huge delay. Do you remember if this happen using the library in a project or does it happens within the library itself?

Note: will reopen this issue when I obtain an answer.
