### ISSUE TITLE
Paths to assets

### ISSUE THREAD

**Issue by saminnet** [rmariuzzo/react-new-window#59]
Is there a way to preserve the paths to assets like (png,svg,..) when opening a new window? 

none of my `<img>` tags can resolve `src` filed.

**Comment by burnmaniac** [comment]
I have the same issue, but in my case, I work with SVGs.

The only possible solution I see is to use absolute paths, and not relative.

So, instead of using path like `/assets/something.svg`, we need to use something like `http://foo.bar/assets/something.svg`.

**Comment by gdenisov** [comment]
An alternative approach is to keep the paths relative but set [the base element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) in the page's header. See code sample here: https://github.com/rmariuzzo/react-new-window/issues/104#issuecomment-1341608171
