### ISSUE TITLE
Locating DOM elements using Query Selector

### ISSUE THREAD

**Issue by vishald2509** [rmariuzzo/react-new-window#64]
I was working on one of my project with the same concept where i encountered
it was not working when i tried to use

`document.querySelector(selector)`

I later tried with this npm and realized it has the same issue.

**Comment by rmariuzzo** [comment]
Hey @vishald2509! Sorry for the late reply, I believe you should run that query in the context of the new window.

**Comment by rmariuzzo** [comment]
Using the `onOpen` callback, it will provide the window instance. Then you can:

```tsx
<NewWindow
  onOpen={popup => console.log(popup.document.querySelector('*'))}
/>
