### ISSUE TITLE
Unable to access Redux store instance used in the original window

### ISSUE THREAD

**Issue by FarzadOfficial** [rmariuzzo/react-new-window#65]
Let's say you have Redux store state and for some reason you need to open certain components in new window, the Redux store state works absolutely fine in the original window, however not in the newly opened window via the main window!

I've seen people use local storage for the new window, but that's so much work and I'm sure there must be an easier way to handle this situation...
Would appreciate if anybody has a solution to this! :)

**Comment by einarq** [comment]
Are you sure this is an issue? Seems weird to me. Do you have a sandbox repro for it?
I believe you should have access to whatever context are available from where the portal is rendered (the dom element can be somewhere else, that should be fine).

https://reactjs.org/docs/portals.html#event-bubbling-through-portals
