### ISSUE TITLE
javascript not referenced in the new windows

### ISSUE THREAD

**Issue by delta360-developer** [rmariuzzo/react-new-window#67]
I have a component using the chart.js (https://github.com/jerairrest/react-chartjs-2) plugin in my component. This component does not work when rendered in the new windows since it requires the javascript references. How can I reference the javascript libraries in the new window?

**Comment by rmariuzzo** [comment]
This along with #69 are related. I will need to investigate how feasible copying js references are the same way we do with css files.

**Comment by rmariuzzo** [comment]
Maybe we could provide something on how `react-helmet` works.

**Comment by tommybernaciak** [comment]
@rmariuzzo Do you have any solution for that?

**Comment by rmariuzzo** [comment]
> @rmariuzzo Do you have any solution for that?

Not yet. I'm checking all issues one by one. I will think on a fix regarding this.

For now, will close this one in favor of: https://github.com/rmariuzzo/react-new-window/issues/69
