### ISSUE TITLE
Some features not working after open a new window

### ISSUE THREAD

**Issue by IMM9O** [rmariuzzo/react-new-window#73]
I try to build a Kanban board using react-beautiful-dnd it works fine when the component render in the main window but after goes outer the draggable feature not working any idea what I am missing here or how to make it work

I created a sandbox link to demonstrate my problem pleas check

https://q5mf6.csb.app/

**Comment by tommybernaciak** [comment]
I have the same issue with the same library (react-beautiful-dnd).  @IMM9O Did you find any solution?

**Comment by IMM9O** [comment]
Unfortunately no, @tommybernaciak

**Comment by rmariuzzo** [comment]
Hey there! I'm really sorry for the very long reply. Just checked the sandbox but can't see the use of `NewWindow`. I understand, if the sandbox changed because of the time. Please let me know, if I can still help.
