### ISSUE TITLE
How do I create multiple windows?

### ISSUE THREAD

**Issue by thaindq** [rmariuzzo/react-new-window#8]
I tried something like this but it didn't work. Nothing appeared.
```
{tabs.map((tab, index) => {
    <NewWindow key={index} url={tab.url} title={tab.url}/>;
})}
```

If I put 2 `NewWindow` together like this then it worked normally. 2 windows were opened.
```
<NewWindow  />
<NewWindow  />
```

**Comment by rmariuzzo** [comment]
@thaindq interesting, do you get any error or warning in the dev console?

**Comment by thaindq** [comment]
@rmariuzzo Nothing in the console.

**Comment by rmariuzzo** [comment]
Can you recreate the scenario at https://codesandbox.io/ so I can have something to reproduce and come more quickly with a fix? 🙇

**Comment by thaindq** [comment]
Thanks, I have to go now but I'll try to recreate that on codesandbox later.

**Comment by rmariuzzo** [comment]
Thanks @thaindq ! I'm more than willing to help on this. :-)

**Comment by thaindq** [comment]
Hey @rmariuzzo, I found the bug and it was my fault. I didn't notice that the returning of my arrow function was wrapped by curly braces, so it returns nothing. It should indeed look like this.
```
{tabs.map((tab, index) => 
    <NewWindow key={index} url={tab.url} title={tab.url}/>
}
```
Thank you for your support :D
