### ISSUE TITLE
Refrence/Context of New window needed

### ISSUE THREAD

**Issue by kn-karanjeetanand** [rmariuzzo/react-new-window#87]
Let's say I have rendered a new component within `<NewWindow>` component. However, document object now points to parent window. It doesn't have reference to new window. Now we use `window.open()` here, which returns the reference/context of the parent window. We want to access the document object of the new window. Is there any way possible to do so using this component?

**Comment by kvarforl** [comment]
A little late, but this thread might help you: https://github.com/rmariuzzo/react-new-window/issues/34#issuecomment-651939230
