### ISSUE TITLE
Window getting closed on click of the contents inside the window 

### ISSUE THREAD

**Issue by afkcodes** [rmariuzzo/react-new-window#92]
Te window is getting closed when i click on the content of the window tried with the default example as well.
i am using next js 11 and react 17

**Comment by rmariuzzo** [comment]
Hey there! Thanks for taking the time to create this issue. I apologize for the long reply. I'm not able to reproduce this issue. Not sure, if something changed with recent fixed that I have applied.

If it still happen, please reopen the issue 🙇
